/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.controller;

import com.volunteer.dto.Error;
import com.volunteer.dto.EventsIndividualEventIdParticipantsUserIdReviewPostRequest;
import com.volunteer.dto.EventsMassIdParticipantsGet200Response;
import com.volunteer.dto.EventsMassIdRequestsGet200ResponseInner;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T11:02:32.604251800+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "participation", description = "Участие в заявках")
public interface ParticipationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_EVENTS_INDIVIDUAL_EVENT_ID_PARTICIPANTS_USER_ID_REVIEW_POST = "/events/individual/{eventId}/participants/{userId}/review";
    /**
     * POST /events/individual/{eventId}/participants/{userId}/review : Оставление отзыва об участнике индивидуальной заявки
     * Автор индивидуальной заявки оставляет отзыв о волонтере после выполнения работы
     *
     * @param eventId Уникальный идентификатор заявки (required)
     * @param userId Уникальный идентификатор волонтера (required)
     * @param eventsIndividualEventIdParticipantsUserIdReviewPostRequest  (required)
     * @return Отзыв успешно добавлен (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (пользователь не автор заявки или заявка не завершена) (status code 403)
     *         or Заявка или пользователь не найдены (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualEventIdParticipantsUserIdReviewPost",
        summary = "Оставление отзыва об участнике индивидуальной заявки",
        description = "Автор индивидуальной заявки оставляет отзыв о волонтере после выполнения работы",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Отзыв успешно добавлен"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (пользователь не автор заявки или заявка не завершена)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка или пользователь не найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_EVENT_ID_PARTICIPANTS_USER_ID_REVIEW_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> eventsIndividualEventIdParticipantsUserIdReviewPost(
        @NotNull @Parameter(name = "eventId", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("eventId") Integer eventId,
        @NotNull @Parameter(name = "userId", description = "Уникальный идентификатор волонтера", required = true, in = ParameterIn.PATH) @PathVariable("userId") Integer userId,
        @Parameter(name = "EventsIndividualEventIdParticipantsUserIdReviewPostRequest", description = "", required = true) @Valid @RequestBody EventsIndividualEventIdParticipantsUserIdReviewPostRequest eventsIndividualEventIdParticipantsUserIdReviewPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_EVENT_ID_REQUESTS_REQUEST_ID_ACCEPT_POST = "/events/individual/{eventId}/requests/{requestId}/accept";
    /**
     * POST /events/individual/{eventId}/requests/{requestId}/accept : Принятие запроса на участие в индивидуальной заявке
     * Автор заявки принимает запрос волонтера на участие
     *
     * @param eventId Уникальный идентификатор заявки (required)
     * @param requestId Уникальный идентификатор запроса (required)
     * @return Запрос успешно принят (status code 200)
     *         or Ошибка (например, достигнут лимит участников) (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Заявка или запрос не найдены (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualEventIdRequestsRequestIdAcceptPost",
        summary = "Принятие запроса на участие в индивидуальной заявке",
        description = "Автор заявки принимает запрос волонтера на участие",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно принят"),
            @ApiResponse(responseCode = "400", description = "Ошибка (например, достигнут лимит участников)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка или запрос не найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_EVENT_ID_REQUESTS_REQUEST_ID_ACCEPT_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsIndividualEventIdRequestsRequestIdAcceptPost(
        @NotNull @Parameter(name = "eventId", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("eventId") Integer eventId,
        @NotNull @Parameter(name = "requestId", description = "Уникальный идентификатор запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_EVENT_ID_REQUESTS_REQUEST_ID_REJECT_POST = "/events/individual/{eventId}/requests/{requestId}/reject";
    /**
     * POST /events/individual/{eventId}/requests/{requestId}/reject : Отклонение запроса на участие в индивидуальной заявке
     * Автор заявки отклоняет запрос волонтера на участие
     *
     * @param eventId Уникальный идентификатор заявки (required)
     * @param requestId Уникальный идентификатор запроса (required)
     * @return Запрос успешно отклонен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Заявка или запрос не найдены (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualEventIdRequestsRequestIdRejectPost",
        summary = "Отклонение запроса на участие в индивидуальной заявке",
        description = "Автор заявки отклоняет запрос волонтера на участие",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно отклонен"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка или запрос не найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_EVENT_ID_REQUESTS_REQUEST_ID_REJECT_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsIndividualEventIdRequestsRequestIdRejectPost(
        @NotNull @Parameter(name = "eventId", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("eventId") Integer eventId,
        @NotNull @Parameter(name = "requestId", description = "Уникальный идентификатор запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_PARTICIPANTS_GET = "/events/individual/{id}/participants";
    /**
     * GET /events/individual/{id}/participants : Получение списка участников индивидуальной заявки
     * Автор заявки получает список участников
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Список участников успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (пользователь не является автором) (status code 403)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdParticipantsGet",
        summary = "Получение списка участников индивидуальной заявки",
        description = "Автор заявки получает список участников",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список участников успешно получен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventsMassIdParticipantsGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (пользователь не является автором)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_ID_PARTICIPANTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<EventsMassIdParticipantsGet200Response> eventsIndividualIdParticipantsGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalCount\" : 0, \"participants\" : [ { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_PARTICIPATE_POST = "/events/individual/{id}/participate";
    /**
     * POST /events/individual/{id}/participate : Подать заявку на участие в индивидуальной заявке
     * Авторизованный пользователь подает заявку на участие в индивидуальной волонтерской заявке
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Заявка на участие успешно подана (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdParticipatePost",
        summary = "Подать заявку на участие в индивидуальной заявке",
        description = "Авторизованный пользователь подает заявку на участие в индивидуальной волонтерской заявке",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Заявка на участие успешно подана"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_ID_PARTICIPATE_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsIndividualIdParticipatePost(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_REQUESTS_GET = "/events/individual/{id}/requests";
    /**
     * GET /events/individual/{id}/requests : Получение списка запросов на участие в индивидуальной заявке
     * Автор заявки получает список запросов на участие для принятия/отклонения
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Список запросов успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdRequestsGet",
        summary = "Получение списка запросов на участие в индивидуальной заявке",
        description = "Автор заявки получает список запросов на участие для принятия/отклонения",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список запросов успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventsMassIdRequestsGet200ResponseInner.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ParticipationApi.PATH_EVENTS_INDIVIDUAL_ID_REQUESTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventsMassIdRequestsGet200ResponseInner>> eventsIndividualIdRequestsGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"requestId\" : 0, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"applicationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"PENDING\" }, { \"requestId\" : 0, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"applicationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"PENDING\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_EVENT_ID_REQUESTS_REQUEST_ID_ACCEPT_POST = "/events/mass/{eventId}/requests/{requestId}/accept";
    /**
     * POST /events/mass/{eventId}/requests/{requestId}/accept : Принятие запроса на участие в массовом мероприятии
     * Представитель организации принимает запрос волонтера на участие
     *
     * @param eventId Уникальный идентификатор мероприятия (required)
     * @param requestId Уникальный идентификатор запроса (required)
     * @return Запрос успешно принят (status code 200)
     *         or Ошибка (например, достигнут лимит участников) (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Мероприятие или запрос не найдены (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassEventIdRequestsRequestIdAcceptPost",
        summary = "Принятие запроса на участие в массовом мероприятии",
        description = "Представитель организации принимает запрос волонтера на участие",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно принят"),
            @ApiResponse(responseCode = "400", description = "Ошибка (например, достигнут лимит участников)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие или запрос не найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_MASS_EVENT_ID_REQUESTS_REQUEST_ID_ACCEPT_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsMassEventIdRequestsRequestIdAcceptPost(
        @NotNull @Parameter(name = "eventId", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("eventId") Integer eventId,
        @NotNull @Parameter(name = "requestId", description = "Уникальный идентификатор запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_EVENT_ID_REQUESTS_REQUEST_ID_REJECT_POST = "/events/mass/{eventId}/requests/{requestId}/reject";
    /**
     * POST /events/mass/{eventId}/requests/{requestId}/reject : Отклонение запроса на участие в массовом мероприятии
     * Представитель организации отклоняет запрос волонтера на участие
     *
     * @param eventId Уникальный идентификатор мероприятия (required)
     * @param requestId Уникальный идентификатор запроса (required)
     * @return Запрос успешно отклонен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Мероприятие или запрос не найдены (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassEventIdRequestsRequestIdRejectPost",
        summary = "Отклонение запроса на участие в массовом мероприятии",
        description = "Представитель организации отклоняет запрос волонтера на участие",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно отклонен"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие или запрос не найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_MASS_EVENT_ID_REQUESTS_REQUEST_ID_REJECT_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsMassEventIdRequestsRequestIdRejectPost(
        @NotNull @Parameter(name = "eventId", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("eventId") Integer eventId,
        @NotNull @Parameter(name = "requestId", description = "Уникальный идентификатор запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_PARTICIPANTS_GET = "/events/mass/{id}/participants";
    /**
     * GET /events/mass/{id}/participants : Получение списка участников массового мероприятия
     * Автор мероприятия или представители организации получают список участников
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Список участников успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (пользователь не является автором/представителем организации) (status code 403)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdParticipantsGet",
        summary = "Получение списка участников массового мероприятия",
        description = "Автор мероприятия или представители организации получают список участников",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список участников успешно получен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventsMassIdParticipantsGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (пользователь не является автором/представителем организации)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ParticipationApi.PATH_EVENTS_MASS_ID_PARTICIPANTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<EventsMassIdParticipantsGet200Response> eventsMassIdParticipantsGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalCount\" : 0, \"participants\" : [ { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_PARTICIPATE_POST = "/events/mass/{id}/participate";
    /**
     * POST /events/mass/{id}/participate : Подать заявку на участие в массовом мероприятии
     * Авторизованный пользователь подает заявку на участие в массовом волонтерском мероприятии
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Заявка на участие успешно подана (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdParticipatePost",
        summary = "Подать заявку на участие в массовом мероприятии",
        description = "Авторизованный пользователь подает заявку на участие в массовом волонтерском мероприятии",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Заявка на участие успешно подана"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ParticipationApi.PATH_EVENTS_MASS_ID_PARTICIPATE_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsMassIdParticipatePost(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_REQUESTS_GET = "/events/mass/{id}/requests";
    /**
     * GET /events/mass/{id}/requests : Получение списка запросов на участие в массовом мероприятии
     * Представители организации получают список запросов на участие для принятия/отклонения
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Список запросов успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (status code 403)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdRequestsGet",
        summary = "Получение списка запросов на участие в массовом мероприятии",
        description = "Представители организации получают список запросов на участие для принятия/отклонения",
        tags = { "participation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список запросов успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventsMassIdRequestsGet200ResponseInner.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ParticipationApi.PATH_EVENTS_MASS_ID_REQUESTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventsMassIdRequestsGet200ResponseInner>> eventsMassIdRequestsGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"requestId\" : 0, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"applicationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"PENDING\" }, { \"requestId\" : 0, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"applicationDate\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"PENDING\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
