/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.participation.controller;

import com.volunteer.common.controller.ApiUtil;
import com.volunteer.event.dto.CreateIndividualEventRequest;
import com.volunteer.event.dto.CreateMassEventRequest;
import org.springframework.format.annotation.DateTimeFormat;
import com.volunteer.common.dto.Error;
import com.volunteer.entity.IndividualEvent;
import java.time.LocalDate;
import java.util.Map;
import com.volunteer.entity.MassEvent;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T11:02:32.604251800+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "requests", description = "Заявки (индивидуальные и корпоративные)")
public interface RequestsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_EVENTS_INDIVIDUAL_GET = "/events/individual";
    /**
     * GET /events/individual : Получение списка индивидуальных заявок
     * Возвращает список всех индивидуальных заявок с возможностью фильтрации по параметрам
     *
     * @param title Поиск по названию заявки (частичное совпадение) (optional)
     * @param dateFrom Поиск заявок начинающихся с указанной даты (optional)
     * @param dateTo Поиск заявок заканчивающихся до указанной даты (optional)
     * @param organisationId Поиск по ID организации (если заявка от организации) (optional)
     * @return Список индивидуальных заявок успешно получен (status code 200)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualGet",
        summary = "Получение списка индивидуальных заявок",
        description = "Возвращает список всех индивидуальных заявок с возможностью фильтрации по параметрам",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список индивидуальных заявок успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = IndividualEvent.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_INDIVIDUAL_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<IndividualEvent>> eventsIndividualGet(
        @Parameter(name = "title", description = "Поиск по названию заявки (частичное совпадение)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "title", required = false) @Nullable String title,
        @Parameter(name = "dateFrom", description = "Поиск заявок начинающихся с указанной даты", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateFrom,
        @Parameter(name = "dateTo", description = "Поиск заявок заканчивающихся до указанной даты", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateTo,
        @Parameter(name = "organisationId", description = "Поиск по ID организации (если заявка от организации)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "organisationId", required = false) @Nullable Integer organisationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, { \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_GET = "/events/individual/{id}";
    /**
     * GET /events/individual/{id} : Получение деталей индивидуальной заявки
     * Возвращает детальную информацию об индивидуальной заявке по ID
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Детали заявки успешно получены (status code 200)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdGet",
        summary = "Получение деталей индивидуальной заявки",
        description = "Возвращает детальную информацию об индивидуальной заявке по ID",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Детали заявки успешно получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = IndividualEvent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_INDIVIDUAL_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<IndividualEvent> eventsIndividualIdGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_PARAMETERS_GET = "/events/individual/{id}/parameters";
    /**
     * GET /events/individual/{id}/parameters : Получение параметров индивидуальной заявки
     * Возвращает дополнительные параметры индивидуальной заявки по ID
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Параметры заявки успешно получены (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdParametersGet",
        summary = "Получение параметров индивидуальной заявки",
        description = "Возвращает дополнительные параметры индивидуальной заявки по ID",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Параметры заявки успешно получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Map.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_INDIVIDUAL_ID_PARAMETERS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Map<String, String>> eventsIndividualIdParametersGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_PUT = "/events/individual/{id}";
    /**
     * PUT /events/individual/{id} : Редактирование индивидуальной заявки
     * Автор заявки редактирует свою индивидуальную заявку
     *
     * @param id Уникальный идентификатор заявки (required)
     * @param createIndividualEventRequest  (required)
     * @return Заявка успешно обновлена (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (пользователь не является автором заявки) (status code 403)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdPut",
        summary = "Редактирование индивидуальной заявки",
        description = "Автор заявки редактирует свою индивидуальную заявку",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Заявка успешно обновлена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = IndividualEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (пользователь не является автором заявки)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = RequestsApi.PATH_EVENTS_INDIVIDUAL_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<IndividualEvent> eventsIndividualIdPut(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "CreateIndividualEventRequest", description = "", required = true) @Valid @RequestBody CreateIndividualEventRequest createIndividualEventRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_POST = "/events/individual";
    /**
     * POST /events/individual : Создание индивидуальной заявки
     * Авторизованный пользователь создает новую индивидуальную волонтерскую заявку
     *
     * @param createIndividualEventRequest  (required)
     * @return Заявка успешно создана (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualPost",
        summary = "Создание индивидуальной заявки",
        description = "Авторизованный пользователь создает новую индивидуальную волонтерскую заявку",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Заявка успешно создана", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = IndividualEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RequestsApi.PATH_EVENTS_INDIVIDUAL_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<IndividualEvent> eventsIndividualPost(
        @Parameter(name = "CreateIndividualEventRequest", description = "", required = true) @Valid @RequestBody CreateIndividualEventRequest createIndividualEventRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_GET = "/events/mass";
    /**
     * GET /events/mass : Получение списка массовых мероприятий
     * Возвращает список всех массовых волонтерских мероприятий с возможностью фильтрации по параметрам
     *
     * @param title Поиск по названию мероприятия (частичное совпадение) (optional)
     * @param dateFrom Поиск мероприятий начинающихся с указанной даты (optional)
     * @param dateTo Поиск мероприятий заканчивающихся до указанной даты (optional)
     * @param address Поиск по адресу проведения (частичное совпадение) (optional)
     * @param organisationId Поиск по ID организации-организатора (optional)
     * @return Список массовых мероприятий успешно получен (status code 200)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassGet",
        summary = "Получение списка массовых мероприятий",
        description = "Возвращает список всех массовых волонтерских мероприятий с возможностью фильтрации по параметрам",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список массовых мероприятий успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = MassEvent.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_MASS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<MassEvent>> eventsMassGet(
        @Parameter(name = "title", description = "Поиск по названию мероприятия (частичное совпадение)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "title", required = false) @Nullable String title,
        @Parameter(name = "dateFrom", description = "Поиск мероприятий начинающихся с указанной даты", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateFrom,
        @Parameter(name = "dateTo", description = "Поиск мероприятий заканчивающихся до указанной даты", in = ParameterIn.QUERY) @Valid @RequestParam(value = "dateTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate dateTo,
        @Parameter(name = "address", description = "Поиск по адресу проведения (частичное совпадение)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "address", required = false) @Nullable String address,
        @Parameter(name = "organisationId", description = "Поиск по ID организации-организатора", in = ParameterIn.QUERY) @Valid @RequestParam(value = "organisationId", required = false) @Nullable Integer organisationId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_GET = "/events/mass/{id}";
    /**
     * GET /events/mass/{id} : Получение деталей массового мероприятия
     * Возвращает детальную информацию о массовом мероприятии по ID
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Детали мероприятия успешно получены (status code 200)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdGet",
        summary = "Получение деталей массового мероприятия",
        description = "Возвращает детальную информацию о массовом мероприятии по ID",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Детали мероприятия успешно получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MassEvent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_MASS_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<MassEvent> eventsMassIdGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_PARAMETERS_GET = "/events/mass/{id}/parameters";
    /**
     * GET /events/mass/{id}/parameters : Получение параметров массового мероприятия
     * Возвращает дополнительные параметры массового мероприятия по ID
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Параметры мероприятия успешно получены (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdParametersGet",
        summary = "Получение параметров массового мероприятия",
        description = "Возвращает дополнительные параметры массового мероприятия по ID",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Параметры мероприятия успешно получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Map.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RequestsApi.PATH_EVENTS_MASS_ID_PARAMETERS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Map<String, String>> eventsMassIdParametersGet(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_PUT = "/events/mass/{id}";
    /**
     * PUT /events/mass/{id} : Редактирование массового мероприятия
     * Представитель организации редактирует массовое мероприятие своей организации
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @param createMassEventRequest  (required)
     * @return Мероприятие успешно обновлено (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ORG_REPRESENTATIVE и принадлежность к организации) (status code 403)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdPut",
        summary = "Редактирование массового мероприятия",
        description = "Представитель организации редактирует массовое мероприятие своей организации",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Мероприятие успешно обновлено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MassEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ORG_REPRESENTATIVE и принадлежность к организации)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = RequestsApi.PATH_EVENTS_MASS_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<MassEvent> eventsMassIdPut(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "CreateMassEventRequest", description = "", required = true) @Valid @RequestBody CreateMassEventRequest createMassEventRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_POST = "/events/mass";
    /**
     * POST /events/mass : Создание массового мероприятия
     * Представитель организации создает новое массовое волонтерское мероприятие от имени своей организации
     *
     * @param createMassEventRequest  (required)
     * @return Мероприятие успешно создано (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ORG_REPRESENTATIVE) (status code 403)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassPost",
        summary = "Создание массового мероприятия",
        description = "Представитель организации создает новое массовое волонтерское мероприятие от имени своей организации",
        tags = { "requests" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Мероприятие успешно создано", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MassEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ORG_REPRESENTATIVE)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RequestsApi.PATH_EVENTS_MASS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<MassEvent> eventsMassPost(
        @Parameter(name = "CreateMassEventRequest", description = "", required = true) @Valid @RequestBody CreateMassEventRequest createMassEventRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
