/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.controller;

import com.volunteer.dto.AdminOrganizationRequestsRequestIdRejectPostRequest;
import com.volunteer.dto.CreateOrganizationRequest;
import com.volunteer.dto.Error;
import org.springframework.lang.Nullable;
import com.volunteer.dto.Organization;
import com.volunteer.dto.OrganizationRoleRequestItem;
import com.volunteer.dto.UpdateUserRoleRequest;
import com.volunteer.dto.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T11:02:32.604251800+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "admin", description = "Административные функции")
public interface AdminApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ADMIN_ORGANIZATION_REQUESTS_GET = "/admin/organization-requests";
    /**
     * GET /admin/organization-requests : Получение списка запросов на статус ПрОрг
     * Администратор получает список всех запросов на получение статуса представителя организации для их рассмотрения
     *
     * @param status Фильтр по статусу запросов (optional, default to PENDING)
     * @return Список запросов успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationRequestsGet",
        summary = "Получение списка запросов на статус ПрОрг",
        description = "Администратор получает список всех запросов на получение статуса представителя организации для их рассмотрения",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список запросов успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OrganizationRoleRequestItem.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdminApi.PATH_ADMIN_ORGANIZATION_REQUESTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<OrganizationRoleRequestItem>> adminOrganizationRequestsGet(
        @Parameter(name = "status", description = "Фильтр по статусу запросов", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false, defaultValue = "PENDING") String status
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"organizationId\" : 1, \"organizationDescription\" : \"organizationDescription\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"organizationAddress\" : \"organizationAddress\", \"requestType\" : \"EXISTING\", \"organizationName\" : \"organizationName\", \"id\" : 0, \"userId\" : 6, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"status\" : \"PENDING\" }, { \"organizationId\" : 1, \"organizationDescription\" : \"organizationDescription\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"organizationAddress\" : \"organizationAddress\", \"requestType\" : \"EXISTING\", \"organizationName\" : \"organizationName\", \"id\" : 0, \"userId\" : 6, \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"status\" : \"PENDING\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATION_REQUESTS_REQUEST_ID_APPROVE_POST = "/admin/organization-requests/{requestId}/approve";
    /**
     * POST /admin/organization-requests/{requestId}/approve : Одобрение запроса на статус ПрОрг
     * Администратор одобряет запрос пользователя на получение статуса представителя организации
     *
     * @param requestId ID запроса (required)
     * @return Запрос успешно одобрен, пользователь получил статус ПрОрг (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Запрос не найден (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationRequestsRequestIdApprovePost",
        summary = "Одобрение запроса на статус ПрОрг",
        description = "Администратор одобряет запрос пользователя на получение статуса представителя организации",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно одобрен, пользователь получил статус ПрОрг"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрос не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_ADMIN_ORGANIZATION_REQUESTS_REQUEST_ID_APPROVE_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> adminOrganizationRequestsRequestIdApprovePost(
        @NotNull @Parameter(name = "requestId", description = "ID запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATION_REQUESTS_REQUEST_ID_REJECT_POST = "/admin/organization-requests/{requestId}/reject";
    /**
     * POST /admin/organization-requests/{requestId}/reject : Отклонение запроса на статус ПрОрг
     * Администратор отклоняет запрос пользователя на получение статуса представителя организации
     *
     * @param requestId ID запроса (required)
     * @param adminOrganizationRequestsRequestIdRejectPostRequest  (optional)
     * @return Запрос успешно отклонен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Запрос не найден (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationRequestsRequestIdRejectPost",
        summary = "Отклонение запроса на статус ПрОрг",
        description = "Администратор отклоняет запрос пользователя на получение статуса представителя организации",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос успешно отклонен"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрос не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_ADMIN_ORGANIZATION_REQUESTS_REQUEST_ID_REJECT_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> adminOrganizationRequestsRequestIdRejectPost(
        @NotNull @Parameter(name = "requestId", description = "ID запроса", required = true, in = ParameterIn.PATH) @PathVariable("requestId") Integer requestId,
        @Parameter(name = "AdminOrganizationRequestsRequestIdRejectPostRequest", description = "") @Valid @RequestBody(required = false) @Nullable AdminOrganizationRequestsRequestIdRejectPostRequest adminOrganizationRequestsRequestIdRejectPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATIONS_GET = "/admin/organizations";
    /**
     * GET /admin/organizations : Получение списка всех организаций (для администратора)
     * Администратор получает расширенный список всех организаций с полной информацией
     *
     * @return Список организаций успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationsGet",
        summary = "Получение списка всех организаций (для администратора)",
        description = "Администратор получает расширенный список всех организаций с полной информацией",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список организаций успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Organization.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdminApi.PATH_ADMIN_ORGANIZATIONS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Organization>> adminOrganizationsGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"address\" : \"address\", \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }, { \"address\" : \"address\", \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATIONS_ID_DELETE = "/admin/organizations/{id}";
    /**
     * DELETE /admin/organizations/{id} : Удаление организации
     * Администратор удаляет организацию из системы
     *
     * @param id ID организации (required)
     * @return Организация успешно удалена (status code 204)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Организация не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationsIdDelete",
        summary = "Удаление организации",
        description = "Администратор удаляет организацию из системы",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Организация успешно удалена"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Организация не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AdminApi.PATH_ADMIN_ORGANIZATIONS_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> adminOrganizationsIdDelete(
        @NotNull @Parameter(name = "id", description = "ID организации", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATIONS_ID_PUT = "/admin/organizations/{id}";
    /**
     * PUT /admin/organizations/{id} : Редактирование организации
     * Администратор изменяет информацию об организации (название, описание, адрес)
     *
     * @param id ID организации (required)
     * @param createOrganizationRequest  (required)
     * @return Организация успешно обновлена (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Организация не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationsIdPut",
        summary = "Редактирование организации",
        description = "Администратор изменяет информацию об организации (название, описание, адрес)",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Организация успешно обновлена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Organization.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Организация не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AdminApi.PATH_ADMIN_ORGANIZATIONS_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Organization> adminOrganizationsIdPut(
        @NotNull @Parameter(name = "id", description = "ID организации", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "CreateOrganizationRequest", description = "", required = true) @Valid @RequestBody CreateOrganizationRequest createOrganizationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"address\", \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_ORGANIZATIONS_POST = "/admin/organizations";
    /**
     * POST /admin/organizations : Создание новой организации
     * Администратор добавляет новую организацию в систему
     *
     * @param createOrganizationRequest  (required)
     * @return Организация успешно создана (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminOrganizationsPost",
        summary = "Создание новой организации",
        description = "Администратор добавляет новую организацию в систему",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Организация успешно создана", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Organization.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_ADMIN_ORGANIZATIONS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Organization> adminOrganizationsPost(
        @Parameter(name = "CreateOrganizationRequest", description = "", required = true) @Valid @RequestBody CreateOrganizationRequest createOrganizationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : \"address\", \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_ADMIN_USERS_USER_ID_ROLE_PUT = "/admin/users/{userId}/role";
    /**
     * PUT /admin/users/{userId}/role : Изменение роли пользователя
     * Администратор изменяет роль учетной записи АП на ПрОрг и наоборот, а также указывает организацию для ПрОрг
     *
     * @param userId ID пользователя (required)
     * @param updateUserRoleRequest  (required)
     * @return Роль пользователя успешно изменена (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Пользователь не найден (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "adminUsersUserIdRolePut",
        summary = "Изменение роли пользователя",
        description = "Администратор изменяет роль учетной записи АП на ПрОрг и наоборот, а также указывает организацию для ПрОрг",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Роль пользователя успешно изменена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Пользователь не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AdminApi.PATH_ADMIN_USERS_USER_ID_ROLE_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<User> adminUsersUserIdRolePut(
        @NotNull @Parameter(name = "userId", description = "ID пользователя", required = true, in = ParameterIn.PATH) @PathVariable("userId") Integer userId,
        @Parameter(name = "UpdateUserRoleRequest", description = "", required = true) @Valid @RequestBody UpdateUserRoleRequest updateUserRoleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_INDIVIDUAL_ID_DELETE = "/events/individual/{id}";
    /**
     * DELETE /events/individual/{id} : Удаление индивидуальной заявки
     * Администратор удаляет индивидуальную заявку в целях модерации
     *
     * @param id Уникальный идентификатор заявки (required)
     * @return Заявка успешно удалена (status code 204)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Заявка не найдена (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsIndividualIdDelete",
        summary = "Удаление индивидуальной заявки",
        description = "Администратор удаляет индивидуальную заявку в целях модерации",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Заявка успешно удалена"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Заявка не найдена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AdminApi.PATH_EVENTS_INDIVIDUAL_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsIndividualIdDelete(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор заявки", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EVENTS_MASS_ID_DELETE = "/events/mass/{id}";
    /**
     * DELETE /events/mass/{id} : Удаление массового мероприятия
     * Администратор удаляет массовое мероприятие в целях модерации
     *
     * @param id Уникальный идентификатор мероприятия (required)
     * @return Мероприятие успешно удалено (status code 204)
     *         or Неавторизованный доступ (status code 401)
     *         or Доступ запрещен (требуется роль ADMIN) (status code 403)
     *         or Мероприятие не найдено (status code 404)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "eventsMassIdDelete",
        summary = "Удаление массового мероприятия",
        description = "Администратор удаляет массовое мероприятие в целях модерации",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Мероприятие успешно удалено"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Доступ запрещен (требуется роль ADMIN)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Мероприятие не найдено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AdminApi.PATH_EVENTS_MASS_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eventsMassIdDelete(
        @NotNull @Parameter(name = "id", description = "Уникальный идентификатор мероприятия", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
