/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.api;

import com.volunteer.model.AuthResponse;
import com.volunteer.model.Error;
import com.volunteer.model.LoginRequest;
import org.springframework.lang.Nullable;
import com.volunteer.model.RegisterRequest;
import java.net.URI;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T10:36:20.114917+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "auth", description = "Аутентификация и авторизация")
public interface AuthApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_AUTH_LOGIN_POST = "/auth/login";
    /**
     * POST /auth/login
     * Вход пользователя через email и пароль
     *
     * @param loginRequest  (required)
     * @return Пользователь успешно вошел (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "authLoginPost",
        description = "Вход пользователя через email и пароль",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Пользователь успешно вошел", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_AUTH_LOGIN_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> authLoginPost(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_AUTH_LOGOUT_POST = "/auth/logout";
    /**
     * POST /auth/logout : Выход пользователя
     * Завершает сеанс пользователя, инвалидируя токен
     *
     * @return Пользователь успешно вышел (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "authLogoutPost",
        summary = "Выход пользователя",
        description = "Завершает сеанс пользователя, инвалидируя токен",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Пользователь успешно вышел"),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_AUTH_LOGOUT_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> authLogoutPost(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_AUTH_OAUTH2_PROVIDER_AUTHORIZE_GET = "/auth/oauth2/{provider}/authorize";
    /**
     * GET /auth/oauth2/{provider}/authorize : OAuth2 авторизация
     * Перенаправляет пользователя на страницу провайдера (VK, Yandex)
     *
     * @param provider  (required)
     * @param redirectUri URL для возврата после авторизации (required)
     * @return Перенаправление на страницу провайдера (status code 302)
     *         or Ошибка валидации данных (status code 400)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "authOauth2ProviderAuthorizeGet",
        summary = "OAuth2 авторизация",
        description = "Перенаправляет пользователя на страницу провайдера (VK, Yandex)",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Перенаправление на страницу провайдера"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_AUTH_OAUTH2_PROVIDER_AUTHORIZE_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> authOauth2ProviderAuthorizeGet(
        @NotNull @Parameter(name = "provider", description = "", required = true, in = ParameterIn.PATH) @PathVariable("provider") String provider,
        @NotNull @Parameter(name = "redirect_uri", description = "URL для возврата после авторизации", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "redirect_uri", required = true) URI redirectUri
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_AUTH_OAUTH2_PROVIDER_CALLBACK_GET = "/auth/oauth2/{provider}/callback";
    /**
     * GET /auth/oauth2/{provider}/callback : OAuth2 callback
     * Обрабатывает ответ от провайдера и возвращает токен аутентификации
     *
     * @param provider  (required)
     * @param code Код авторизации, полученный от провайдера (required)
     * @param state Состояние для предотвращения CSRF атак (optional)
     * @return Пользователь успешно аутентифицирован (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "authOauth2ProviderCallbackGet",
        summary = "OAuth2 callback",
        description = "Обрабатывает ответ от провайдера и возвращает токен аутентификации",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Пользователь успешно аутентифицирован", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_AUTH_OAUTH2_PROVIDER_CALLBACK_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<AuthResponse> authOauth2ProviderCallbackGet(
        @NotNull @Parameter(name = "provider", description = "", required = true, in = ParameterIn.PATH) @PathVariable("provider") String provider,
        @NotNull @Parameter(name = "code", description = "Код авторизации, полученный от провайдера", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "code", required = true) String code,
        @Parameter(name = "state", description = "Состояние для предотвращения CSRF атак", in = ParameterIn.QUERY) @Valid @RequestParam(value = "state", required = false) @Nullable String state
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_AUTH_REGISTER_POST = "/auth/register";
    /**
     * POST /auth/register
     * Регистрация нового пользователя через email и пароль
     *
     * @param registerRequest  (required)
     * @return Пользователь успешно зарегистрирован (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "authRegisterPost",
        description = "Регистрация нового пользователя через email и пароль",
        tags = { "auth" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Пользователь успешно зарегистрирован", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_AUTH_REGISTER_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> authRegisterPost(
        @Parameter(name = "RegisterRequest", description = "", required = true) @Valid @RequestBody RegisterRequest registerRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
