/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.api;

import com.volunteer.model.Error;
import com.volunteer.model.LeaderboardResponse;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T10:36:20.114917+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "leaderboard", description = "Список лидеров")
public interface LeaderboardApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_LEADERBOARD_GET = "/leaderboard";
    /**
     * GET /leaderboard : Получение списка лидеров
     * Возвращает список лидеров волонтерской активности. Если пользователь авторизован, дополнительно возвращается его позиция в рейтинге. Доступен как для авторизованных, так и для неавторизованных пользователей. 
     *
     * @param limit Количество записей в списке лидеров (optional, default to 100)
     * @return Список лидеров успешно получен (status code 200)
     *         or Ошибка валидации параметров (status code 400)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "leaderboardGet",
        summary = "Получение списка лидеров",
        description = "Возвращает список лидеров волонтерской активности. Если пользователь авторизован, дополнительно возвращается его позиция в рейтинге. Доступен как для авторизованных, так и для неавторизованных пользователей. ",
        tags = { "leaderboard" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список лидеров успешно получен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LeaderboardResponse.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"leaderboard\":[{\"rank\":1,\"userId\":123,\"fullName\":\"Иванов Иван\",\"score\":150},{\"rank\":2,\"userId\":456,\"fullName\":\"Петров Петр\",\"score\":140}],\"currentUserRank\":null}"
                    ),
                    @ExampleObject(
                        name = "",
                        value = "{\"leaderboard\":[{\"rank\":1,\"userId\":123,\"fullName\":\"Иванов Иван\",\"score\":150},{\"rank\":2,\"userId\":456,\"fullName\":\"Петров Петр\",\"score\":140}],\"currentUserRank\":{\"rank\":45,\"score\":25}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации параметров", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LeaderboardApi.PATH_LEADERBOARD_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<LeaderboardResponse> leaderboardGet(
        @Min(value = 1) @Max(value = 500) @Parameter(name = "limit", description = "Количество записей в списке лидеров", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "100") Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"leaderboard\" : [ { \"score\" : 1, \"rank\" : 0, \"fullName\" : \"fullName\", \"userId\" : 6 }, { \"score\" : 1, \"rank\" : 0, \"fullName\" : \"fullName\", \"userId\" : 6 } ], \"currentUserRank\" : { \"score\" : 5, \"rank\" : 5 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
