/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.volunteer.api;

import com.volunteer.model.Error;
import org.springframework.lang.Nullable;
import com.volunteer.model.OrganizationRoleRequest;
import com.volunteer.model.Review;
import com.volunteer.model.UpdateUserRequest;
import com.volunteer.model.User;
import com.volunteer.model.UsersMeAvatarPost200Response;
import com.volunteer.model.UsersMeEventsGet200Response;
import com.volunteer.model.UsersMeVolunteerBookGet200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-14T10:36:20.114917+03:00[Europe/Moscow]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "users", description = "Управление пользователями")
public interface UsersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_USERS_ME_AVATAR_POST = "/users/me/avatar";
    /**
     * POST /users/me/avatar : Загрузка аватара
     * Авторизованный пользователь загружает свой аватар
     *
     * @param file Файл изображения (JPEG, PNG) (required)
     * @return Аватар успешно загружен (status code 200)
     *         or Ошибка валидации файла (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeAvatarPost",
        summary = "Загрузка аватара",
        description = "Авторизованный пользователь загружает свой аватар",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Аватар успешно загружен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UsersMeAvatarPost200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации файла", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UsersApi.PATH_USERS_ME_AVATAR_POST,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<UsersMeAvatarPost200Response> usersMeAvatarPost(
        @Parameter(name = "file", description = "Файл изображения (JPEG, PNG)", required = true) @RequestPart(value = "file", required = true) MultipartFile file
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"avatarUrl\" : \"avatarUrl\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_EVENTS_GET = "/users/me/events";
    /**
     * GET /users/me/events : Получение списка заявок пользователя
     * Возвращает список заявок, созданных авторизованным пользователем (активных и завершившихся)
     *
     * @param status Фильтр по статусу заявок (optional, default to all)
     * @return Список заявок успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeEventsGet",
        summary = "Получение списка заявок пользователя",
        description = "Возвращает список заявок, созданных авторизованным пользователем (активных и завершившихся)",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список заявок успешно получен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UsersMeEventsGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UsersApi.PATH_USERS_ME_EVENTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<UsersMeEventsGet200Response> usersMeEventsGet(
        @Parameter(name = "status", description = "Фильтр по статусу заявок", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false, defaultValue = "all") String status
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"individualEvents\" : [ { \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, { \"organisationId\" : 7, \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"volunteersRequired\" : 9, \"description\" : \"description\", \"ageRestriction\" : 3, \"id\" : 2, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" } ], \"massEvents\" : [ { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_GET = "/users/me";
    /**
     * GET /users/me : Получение информации о текущем пользователе
     * Возвращает данные личного кабинета авторизованного пользователя
     *
     * @return Данные пользователя успешно получены (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeGet",
        summary = "Получение информации о текущем пользователе",
        description = "Возвращает данные личного кабинета авторизованного пользователя",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Данные пользователя успешно получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UsersApi.PATH_USERS_ME_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<User> usersMeGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_ORGANIZATION_REQUEST_POST = "/users/me/organization-request";
    /**
     * POST /users/me/organization-request : Подача запроса на получение статуса представителя организации
     * Авторизованный пользователь подает запрос на получение статуса ПрОрг, указывая существующую организацию или данные для создания новой
     *
     * @param organizationRoleRequest  (required)
     * @return Запрос успешно подан (status code 201)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Пользователь уже является представителем организации (status code 409)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeOrganizationRequestPost",
        summary = "Подача запроса на получение статуса представителя организации",
        description = "Авторизованный пользователь подает запрос на получение статуса ПрОрг, указывая существующую организацию или данные для создания новой",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Запрос успешно подан"),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Пользователь уже является представителем организации", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UsersApi.PATH_USERS_ME_ORGANIZATION_REQUEST_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> usersMeOrganizationRequestPost(
        @Parameter(name = "OrganizationRoleRequest", description = "", required = true) @Valid @RequestBody OrganizationRoleRequest organizationRoleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_PUT = "/users/me";
    /**
     * PUT /users/me : Редактирование личных данных
     * Авторизованный пользователь редактирует свои личные данные
     *
     * @param updateUserRequest  (required)
     * @return Данные успешно обновлены (status code 200)
     *         or Ошибка валидации данных (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMePut",
        summary = "Редактирование личных данных",
        description = "Авторизованный пользователь редактирует свои личные данные",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Данные успешно обновлены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка валидации данных", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UsersApi.PATH_USERS_ME_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<User> usersMePut(
        @Parameter(name = "UpdateUserRequest", description = "", required = true) @Valid @RequestBody UpdateUserRequest updateUserRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"birthday\" : \"2000-01-23\", \"organisationId\" : 6, \"role\" : \"USER\", \"volunteerHours\" : 1.4658129, \"name\" : \"name\", \"rating\" : 5.962134, \"description\" : \"description\", \"location\" : \"location\", \"id\" : 0, \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_REVIEWS_GET = "/users/me/reviews";
    /**
     * GET /users/me/reviews : Получение отзывов о пользователе
     * Возвращает список отзывов об участии авторизованного пользователя в индивидуальных заявках
     *
     * @return Список отзывов успешно получен (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeReviewsGet",
        summary = "Получение отзывов о пользователе",
        description = "Возвращает список отзывов об участии авторизованного пользователя в индивидуальных заявках",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список отзывов успешно получен", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Review.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UsersApi.PATH_USERS_ME_REVIEWS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Review>> usersMeReviewsGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"reviewedId\" : 1, \"eventId\" : 5, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"reviewerId\" : 6, \"rating\" : 5.637377, \"id\" : 0, \"content\" : \"content\" }, { \"reviewedId\" : 1, \"eventId\" : 5, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"reviewerId\" : 6, \"rating\" : 5.637377, \"id\" : 0, \"content\" : \"content\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USERS_ME_VOLUNTEER_BOOK_GET = "/users/me/volunteer-book";
    /**
     * GET /users/me/volunteer-book : Получение электронной волонтерской книжки
     * Возвращает электронную волонтерскую книжку авторизованного пользователя. Книжка содержит записи об участии в завершенных массовых волонтерских мероприятиях. Записи автоматически добавляются после завершения мероприятия. 
     *
     * @return Волонтерская книжка успешно получена (status code 200)
     *         or Неавторизованный доступ (status code 401)
     *         or Внутренняя ошибка сервера (status code 500)
     */
    @Operation(
        operationId = "usersMeVolunteerBookGet",
        summary = "Получение электронной волонтерской книжки",
        description = "Возвращает электронную волонтерскую книжку авторизованного пользователя. Книжка содержит записи об участии в завершенных массовых волонтерских мероприятиях. Записи автоматически добавляются после завершения мероприятия. ",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Волонтерская книжка успешно получена", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UsersMeVolunteerBookGet200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Неавторизованный доступ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UsersApi.PATH_USERS_ME_VOLUNTEER_BOOK_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<UsersMeVolunteerBookGet200Response> usersMeVolunteerBookGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"entries\" : [ { \"eventId\" : 1, \"completedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"event\" : { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, \"userId\" : 6, \"content\" : \"content\" }, { \"eventId\" : 1, \"completedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 0, \"event\" : { \"organisationId\" : 6, \"address\" : \"address\", \"dateStart\" : \"2000-01-23T04:56:07.000+00:00\", \"workHours\" : 1.4658129, \"volunteersRequired\" : 5, \"description\" : \"description\", \"ageRestriction\" : 5, \"id\" : 0, \"dateEnd\" : \"2000-01-23T04:56:07.000+00:00\", \"title\" : \"title\" }, \"userId\" : 6, \"content\" : \"content\" } ], \"totalHours\" : 5.962134, \"totalEvents\" : 5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
